### PR TITLE
Redesign using BTCPay design guidelines

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by dennisreimann** [comment]
Screenshots of the enhancements. Feeedback welcome :)

dark

light

about

**Review by dennisreimann — APPROVED** [review]

**Comment by pavlenex** [comment]
utACK

**Comment by pavlenex** [comment]
On a side note, it would be good to have message as required in contact form, often people just send the email without the message which makes it hard to distinguish between spammers and actual supporters. Didn't want to open an issue just for this nit.

**Comment by dennisreimann** [comment]
Yeah, let's fix it right away – however, this is some third-party JS which makes the form work, @Kukks do you know the details and can take care?

**Comment by pavlenex** [comment]
It's using form.io afaik.

**Comment by Kukks** [comment]
Fixed it already

**Pull request merged**
