### PR TITLE
Add Past Supporter page

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Zaxounette** [comment]
OKCoin can also be added, if team feels sufficient time has passed.

**Review by dennisreimann — COMMENTED** [review]
BTSE and DG Lab are shown in both lists, that's weird.

Otherwise it LGTM.

**Comment by Kukks** [comment]
> BTSE and DG Lab are shown in both lists, that's weird.
> 
> Otherwise it LGTM.

Yeah, this is a dry run, prepping the secondary page before moving the actual content over.

**Comment by pavlenex** [comment]
> OKCoin can also be added, if team feels sufficient time has passed.

OkCoin expires on MAY 28th.

**Review by pavlenex — COMMENTED** [review]
@Kukks OKCoin logo looks messed up.
Screenshot 2021-04-12 at 11 12 17

**Comment by pavlenex** [comment]
@Kukks can you remove WOS from the past page as they're renewing their support?
Also, can you remove this from the index.html 
```
  <div class="figure p-3">
        <a href="https://www.btse.com" target="_blank" class="text-muted small">
          <img src="assets/btse.svg" alt="Sponsor BTSE" />
          <div class="figure-caption">BTSE</div>
        </a>
      </div>
      <div class="figure p-3">
        <a href="https://www.okcoin.com/" target="_blank" class="text-muted small">
          <img src="assets/okcoin.svg" alt="Sponsor OKCoin" />
          <div class="figure-caption">OKCoin</div>
        </a>
      </div>
      <div class="figure p-3">
        <a href="https://www.dglab.com/en/" target="_blank" class="text-muted small">
          <img src="assets/dglab.svg" alt="Sponsor DG lab" />
          <div class="figure-caption">DG Lab</div>
        </a>
      </div>
```
So we can move do it all in a single PR and merge after the https://github.com/btcpayserver/btcpayserver/pull/2536

**Review by pavlenex — APPROVED** [review]
This one is ready to go after May 28th.

**Pull request merged**
